name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  actions: write
  checks: write
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: npm install
        run: npm i

      - name: build
        run: |
          npm run build
        env:
          GITHUB_PAGES: true

      - name: Push to GitHub
        uses: EndBug/add-and-commit@main
        with:
            # ブランチ名はデフォルトブランチ名にする(main or master)
            branch: main  
            message: ':rocket: Update'